# config.yaml
# possible to add any thing you want, then import it in the HTML
# with {{ config.THING_TO_IMPORT }}

# link to an avatar, then a description of it
AVATAR: "http://website.com/a_picture_of_something.jpg"
AVATAR_DESC: "my picture"

# name, description, and url of website
SITENAME: "QAPC"
DESC: "Queer Art and Porn Collective"
URL: "http://qapcollective.net"
SOURCE: "https://github.com/collectqt/qapc"

# Integrations
GOOGLE_ANALYTICS_CODE: # inside web-app/templates/analytics.html
OPENGRAPH: True # inside web-app/templates/head.html

# Settings
PORT: 5000
