# config.yaml
# var names in ALL CAPS
# booleans are True or False
# most things should be strings
SITENAME: "Lynn Blog"
AVATAR: "http://www.gravatar.com/avatar/b1cde28ce033c8cd6f4be4059efbe00b.png?size=160"
URL: "http://lynncyrin.me"
DESC: "The blog of a Queer, Feminist, Programmer - Lynn Cyrin"
