# config.yaml
# possible to add any thing you want, then import it in the HTML
# with {{ config.THING_TO_IMPORT }}

# link to an avatar, then a description of it
AVATAR: "http://website.com/a_picture_of_something.jpg"
AVATAR_DESC: "my picture"

# name, description, and url of website
SITENAME: "FireStarter"
DESC: "Start a flask site really fast! Like, super fast!!!"
URL: "http://lynncyrin.me"

# Intregrations
GOOGLE_ANALYTICS_CODE: # inside web-app/templates/analytics.html
OPENGRAPH: True # inside web-app/templates/head.html

# Settings
DEBUG: True
PORT: 5000
